# Generated by Django 4.1.2 on 2022-10-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogador', models.CharField(max_length=20)),
                ('telemovel', models.CharField(max_length=12)),
                ('idade', models.CharField(max_length=3)),
                ('data_registro', models.DateTimeField(auto_now=True)),
                ('personagem', models.CharField(max_length=20)),
                ('bg', models.TextField()),
            ],
        ),
    ]
