# Generated by Django 4.1.2 on 2022-10-16 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='Atributos',
            field=models.CharField(default=datetime.datetime(2022, 10, 16, 21, 3, 4, 784349, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='campanha',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('ID', 'Ilha do Desespero'), ('NM', 'Novo Mundo')], default='Pendente', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='classe',
            field=models.CharField(choices=[('Guerreiro', 'Guerreiro'), ('Barbaro', 'Barbaro'), ('Paladino', 'Paladino'), ('Clerigo', 'Clerigo'), ('Mago', 'Mago'), ('Bruxo', 'Bruxo'), ('Ladino', 'Ladino')], default=datetime.datetime(2022, 10, 16, 21, 3, 25, 387166, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='disponivel',
            field=models.CharField(choices=[('Sabado', 'Sabado'), ('Domingo', 'Domingo')], default=datetime.datetime(2022, 10, 16, 21, 4, 33, 828281, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='raca',
            field=models.CharField(choices=[('Humano', 'Humano'), ('Elfo', 'Elfo'), ('Anão', 'Anão'), ('Gnomo', 'Gnomo'), ('Orc', 'Orc')], default=datetime.datetime(2022, 10, 16, 21, 4, 42, 928353, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
    ]
