# Generated by Django 4.1.2 on 2022-10-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_registro_atributos_registro_campanha_registro_classe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='exp_rpg',
            field=models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='registro',
            name='campanha',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Ilha do Desespero', 'Ilha do Desespero'), ('Novo Mundo', 'Novo Mundo')], default='Pendente', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='disponivel',
            field=models.CharField(choices=[('Sabado', 'Sábado'), ('Domingo', 'Domingo')], max_length=20),
        ),
    ]
